sudo: required
services:
  - docker

language: python
rvm:
  - 3.6.7

env:
  - DOCKER_COMPOSE_VERSION=3

script:
  - docker-compose up --build 
  - docker ps


after_script:
  - docker-compose stop
  - docker-compose rm -f
