sudo: required
services:
  - docker

language: python
rvm:
  - 3.6.7

env:
  - DOCKER_COMPOSE_VERSION=3

script:
  - docker-compose up -d 
  - docker ps
#after_success:
  # [START auth]
  # Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
  ##- "openssl aes-256-cbc -K $encrypted_6cbe24f4105f_key -iv $encrypted_6cbe24f4105f_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d"
  # If the SDK is not already cached, download it and unpack it
  ##- if [ ! -d ${HOME}/google-cloud-sdk ]; then export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
  ##    curl https://sdk.cloud.google.com | bash;
  ##  fi
  ##- tar -xzf credentials.tar.gz
  ##- mkdir -p lib
  # Here we use the decrypted service account credentials to authenticate the command line tool
  ##- gcloud auth activate-service-account --key-file client-secret.json
  # [END auth]

after_script:
  - docker-compose stop
  - docker-compose rm -f
