sudo: required
services:
  - docker

language: python
rvm:
  - 3.6.7

env:
  - DOCKER_COMPOSE_VERSION=3

before_install:
  - docker-compose up  -d
  #- docker ps
script:
  - rts_script_1

deploy:
  provider: gae
  keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
  project: "YOUR PROJECT ID"
  skip_cleanup: true

after_script:
  - docker-compose stop
  - docker-compose rm -f
